import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ['latin'] });
const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.className}  antialiased`}
      >
        <Header />
        <div className="px-5 sm:px-16 md:px-28 lg:px-36">
          <Toaster/>
        {children}
        </div>
      </body>
    </html>
  );
}
